### ISSUE TITLE
Tag 0.22?

### ISSUE THREAD

**Issue by jhersh** [seanmiddleditch/libtelnet#22]
Ahoy, it's been quite some time since `0.21`'s release. Would you consider pushing a new tag? This is particularly helpful for me, as I pull libtelnet into my project using CocoaPods and I'd much rather point to a tag (rather than a commit). Thanks!

**Comment by seanmiddleditch** [comment]
Just wanted to comment quickly - the request's not forgotten, I'm just _really_ busy the ol' day job, and tagging a new release is only something I'll do after more thoroughly double-checking the state of master. Apologies.

**Comment by thefallentree** [comment]
@seanmiddleditch  fluffos has been using latest commit for a while now, and it seems pretty OK.

**Comment by thefallentree** [comment]
Now that is the bug we fixed. It's time to put a new release out to notify people to upgrade to this.

**Comment by seanmiddleditch** [comment]
It's on my radar, but I'm pretty busy. Feel free to ping me on this if I don't get to it soon (or send me pull requests to get all the release stuff handled, and then I can tag the release commit).

**Comment by qunying** [comment]
like to know too about a new release tag ^_^

**Comment by seanmiddleditch** [comment]
I'd like to get onto CMake before doing a 0.22, but it's been a few years and we have some good fixes in the pipe. I'm actually working on something telnet-related for the first time in years so I'll try to remember to roll a release for libtelnet soon - please feel free to keep bugging me (or put up a PR prepping the release, e.g. rolling version to 0.22 in develop and the merge request into master) if I continue to slack. :)

**Comment by seanmiddleditch** [comment]
I gave up on getting to CMake in a timely manner so it's tagged and released. :)
