### ISSUE TITLE
undefined behaviour - missing va_end() calls

### ISSUE THREAD

**Issue by illu89** [seanmiddleditch/libtelnet#33]
I did run the code through cppcheck static analysis - it found 2 errors.

```
[libtelnet.c:1387]: (error) va_list 'va2' was opened but not closed by va_end().
[libtelnet.c:1457]: (error) va_list 'va2' was opened but not closed by va_end().
```

Error branches in functions `telnet_vprintf()` and `telnet_raw_vprintf()` do not call `va_end()` for the valist `va2` - this is undefined behaviour.

**Comment by seanmiddleditch** [comment]
Fixed up the remaining case of this with va_copy in telnet_vprintf
