### ISSUE TITLE
telnet clinet

### ISSUE THREAD

**Issue by SouthHalfCents** [seanmiddleditch/libtelnet#38]
the exmaple seens to be telnet server, how can I use the lib to create a telnet client? Can you show some exmaples please?

**Comment by SouthHalfCents** [comment]
I find the telnet-client.c , but I it's for linux

**Comment by seanmiddleditch** [comment]
The client is just a sample, but shows anything you'd need from this library specifically. Anything else you might need out of that is going to be platform-specific terminal handling which is out of scope for this project. If you're looking for ANSI code translation for Windows or a GUI package, you'll need to roll your own or find another library that handles that part.

**Comment by SouthHalfCents** [comment]
Thanks, it's ok now.
