### ISSUE TITLE
Simplify API

### ISSUE THREAD

**Issue by alejandro-colomar** [seanmiddleditch/libtelnet#60]
I was trying to use libtelnet for a program that needs to send messages to a telnet server (a robot), but using it is very complicated.  And the example telnet_client.c is too complicated too to adapt it.  I think the libtelnet API could be made a lot simpler.

I would expect of a library like libtelnet to already provide me with a working socket, instead of me having to open one and pass it to the library.

I don't see any benefit in writing the code to get the socket outside of libtelnet.  It's always going to be the same. Repeating the same code for every program that uses the library isn't good IMHO.

Couldn't this function be used inside libtelnet to provide a socket? :

```
int	alx_tcp_client_open	(const char *restrict server_addr,
				 const char *restrict server_port)
{
	struct protoent	*tcp;
	int		sd;
	struct addrinfo	hint = {0};
	struct addrinfo	*addrs;
	int		status;

	tcp	= getprotobyname("tcp");
	if (!tcp)
		return	-EINVAL;
	hint.ai_family		= AF_UNSPEC;
	hint.ai_socktype	= SOCK_STREAM;
	hint.ai_protocol	= tcp->p_proto;
	status	= getaddrinfo(server_addr, server_port, &hint, &addrs);
	if (status)
		return	-labs(status);

	for (struct addrinfo *ad = addrs; ad; ad = ad->ai_next) {
		sd = socket(ad->ai_family, ad->ai_socktype, ad->ai_protocol);
		if (sd < 0)
			continue;
		if (connect(sd, ad->ai_addr, ad->ai_addrlen))
			goto try_next;
		break;
try_next:
		close(sd);
		sd = -1;
	}
	freeaddrinfo(addrs);

	if (sd < 0)
		return	-errno;
	return	sd;
}
```

I could write that API myself if I understood how libtelnet works, but it's too complicated for me.

I think the library needs some abstraction layers.  For example a layer that handles all the TCP part, and then a simple layer that adds the TELNET part on top of it.

**Comment by Beliriel** [comment]
As I understand it this is a library for handling the TELNET **protocol**. It is not the library's task to manage connections. Yes TELNET is primarily used over the internet but it seems to be not the goal of this project. If you wanted you could write multiple applications which communicate with each other using the TELNET protocol with this library without ever using sockets or network connections. 
You need to manage your buffers yourself.
```
void telnet_recv(telnet_t *telnet, const char *buffer, unsigned int size, void *user_data);
void telnet_send(telnet_t *telnet, const char *buffer, size_t size);
```
I imagine these confuse you? If so be aware that the char* buffer is basically just a byte array and can be used in any manner you like (sockets, interprocess communication or whatever else you want). You need to allocate these buffer arrays yourself and then can use them.

I find it even nice that we got provided with examples (a client, a chat daemon and a proxy).

Note that I am not the original author. Maybe he will weigh in and explain his idea better.

**Comment by alejandro-colomar** [comment]
Ok, my bad.  I didn't know that telnet could be implemented without tcp.  I thought telnet was a protocol on top of tcp. :)

**Comment by Beliriel** [comment]
Well it usually is used that way. Especially in the network stack. And since TELNET doesn't really get used in other ways I get the confusion. I had similar issues.

**Comment by alejandro-colomar** [comment]
Shouldn't a libtelnet-tcp library be written on top of this then? :)

I'd like to do that.  I'll have to decypher libtelnet first, though.

**Comment by thefallentree** [comment]
> Shouldn't a libtelnet-tcp library be written on top of this then? :)
> 
> I'd like to do that. I'll have to decypher libtelnet first, though.

No, I don't think that's in the scope.  if you want an network framework, take an look at libevent, libev or libuv, or libwebsocket(it does raw tcp as well).
