### ISSUE TITLE
Interpreting the tests

### ISSUE THREAD

**Issue by jtenner** [seanmiddleditch/libtelnet#61]
Hey! I just wanted to say thank you for creating this repo. Is there any chance I could get some help interpreting how the tests should be implemented?

Context: I'm compiling this library to web assembly using emscripten for JavaScript developers and wrapping the functions in a `Telnet` class so that it can be used easily.

See: https://github.com/jtenner/libtelnet-ts

Just need to implement the tests manually using JavaScript, but I am having a hard time understanding how the tests are formatted.

Thank you very much for all this work.

**Comment by jtenner** [comment]
So I got the tests working. But I still need some help.

I had a question about how the event output is supposed to work.

If we have a compatibility table like this:

```c
static const telnet_telopt_t telopts[] = {
 { TELNET_TELOPT_BINARY,	TELNET_WILL, TELNET_DO },
 { -1, 0, 0 }
};
```

And then we receive: `IAC DO BINARY`, what events should output?

For reference, the only event that's outputting right now is 

`SEND: IAC WONT BINARY`

**Comment by jtenner** [comment]
Ah. It looks like I was improperly setting up the telopt table. Thanks anyway!

**Comment by thefallentree** [comment]
@jtenner your JS implementations looks promising , I think it could be just integrated directly to this repo or fluffos/libtelnet fork ,   I am going to use it in fluffos anyway

**Comment by jtenner** [comment]
Thank you for that! I'm currently working on setting up the `CompatibilityTable` class better. Perhaps it would be a good idea to set up a slack server or discord server for this project?

**Comment by jtenner** [comment]
@thefallentree The problem with integrating my implementation is that I removed the event handler logic. For instance, all the event routing happens in JavaScript now. All the calls to `telnet->eh()` were directized to the glue code function. I also removed the `userdata` field from the telnet struct because all the user data should live in JavaScript now.
