### ISSUE TITLE
Cannot handle multiple logs

### ISSUE THREAD

**Issue by uddhavdave** [seanmiddleditch/libtelnet#63]
I am using telnet to send logs to a client and the library is causing a crash whenever there are a lot of loglines to send. I am using `telnet_vprintf()`. Is there any way to increase the queue size if there is any? Also is it possible to use UDP here, as sockets are managed by user only. I know telnet is TCP based but its slow for my use case.

**Comment by seanmiddleditch** [comment]
A backtrace for the crash would be helpful. The library just forwards events to your underlying socket handling code for sending data, so it doesn't really handle its own buffers. Specifically for `telnet_vprintf` there is a temporary buffer used if the output is too long to fit in a static buffer, though, which may have a bug. (That approach also isn't the most performant if you're frequently sending long lines; you might want to implement your own vprintf wrapper that reuses and grows an allocated buffer to minimize the number of allocations/deallocations performed)

**Comment by uddhavdave** [comment]
Hey, Thanks for speedy response. I would like to inform that the bug was on my side and i have now solved it. But now i am facing following error on wifi disconnect: 
`E (180759) component_telnet: send: 113 (Software caused connection abort)
E (180769) component_telnet: send: 113 (Software caused connection abort)
`
I am freeing the handle to stop the telnet task but the heap is getting corrupted. So i would like to know what is the proper way to deinit the event handler and stop telnet. Thanks for such a great lib!!

**Comment by seanmiddleditch** [comment]
Those errors look like socket errors to me, which would imply there's perhaps something else going on in your socket handling code.

If you're freeing the telnet_t handle, make sure you're not doing it in a callback from the library; that may well result in some corruption!

If it still seems off, feel free to post a stacktrace with the errors as a new issue and we'll see if we can resolve what's going on.

**Comment by uddhavdave** [comment]
Yes, you're right. I just want to know why the event handler is going on when im doing telnet_free().

**Comment by uddhavdave** [comment]
Sort, i got it. Thanks man. Great Library. Sorry i am a newbie.

**Comment by seanmiddleditch** [comment]
@alphabeta1212 - no worries - we all were new at one time or another, and we're all new to something no matter how experienced we may be elsewhere :)
