### ISSUE TITLE
Missing Visual Studio solution files in tarball

### ISSUE THREAD

**Issue by elanthis** [seanmiddleditch/libtelnet#7]
The autotools rules for "make dist" aren't packaging up the Visual Studio solution files, so they're missing in the release tarballs.

**Comment by yamamushi** [comment]
If you need assistance converting to cmake, I'd be happy giving it a shot.

**Comment by seanmiddleditch** [comment]
I won't turn down the contribution. :)

**Comment by thefallentree** [comment]
nah, There is only one source file...make is perfectly fine...

**Comment by seanmiddleditch** [comment]
@thefallentree: except it's currently _automake_, not just make. Plus we have to include separate VS files because automake only supports crufty old GNU-like systems. :)

**Comment by yamamushi** [comment]
I'll be building against Linux and OSX, not sure that I can test against Windows. Are there any specific requirements you'd want in a CMake build, or should I just put something standard together and have you tell me suggestions on where to go from there?
